[package]
resolver = "2"
name = "turbostate"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["sync"], optional = true }
async-recursion = { version = "1.0", optional = true }

[features]
async = ["tokio", "async-recursion"]
from_residual = []
