[package]
name = "turbostate_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0", features = ["nightly"] }
syn = { version = "2.0", features = ["full", "extra-traits"] }
proc-macro-crate = "3.1"
quote = "1.0"
